apiVersion: v2
name: chart-example
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: 1.0.0
dependencies:
  - name: postgresql
    version: 9.2.1
    repository: https://charts.bitnami.com/bitnami